name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: prep
        uses: actions/checkout@v2
      - name: build
        run: ./install-debian.sh
