name: "C/C++ CI"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build
      shell: bash
      run: ./install-debian.sh

  build-macos:
    runs-on: macos-11
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build
      shell: bash
      run: chmod +x install-zerobuild-macos.sh && ./install-zerobuild-macos.sh
